print("If you want to make your own command, you came to the right place, just type ''createcommand''")
print(" ")
console = input("-> ")
print(" ")
if console == "createcommand":
    commandQ = input("What do you want your command to be called? ")
print(" ")
print("Ok so your command will look like this ->", commandQ)
print(" ")
commandQ2 = input("What do you want this to say when you type it? ")
print(" ")
print("Ok so your command will say ->", commandQ2)
print(" ")
test = input("Now try your command! ")
print(" ")
if test == commandQ:
    print(commandQ2)
print(" ")
print(" ")
print("Made by Dino...")
